[package]
name = "dds_bridge"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
tokio = { version = "1.40", features = [ "full" ] }
futures = "0.3"
log = "0.4.22"
colog = "1"
bytes = "1.7"
bincode = "1.3.3"
serde = { version = "1", features = [ "derive" ] }
r2r = "0.9.2"
hashbrown = "0.15.0"