[package]
name = "cli"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
argh = "0.1"
colog = "1"
log = "0.4"
regex = "1"
serde = { version = "1", features = [ "derive" ] }
serde_json = "1"
tempfile = "3"
toposort-scc = "0.5"
