[package]
name = "create_bridge"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1.0"
anyhow = "1.0"
log = "0.4"
tokio = { version = "1.40", features = [ "full" ] }
num_enum = "0.7"
tokio-serial = "5.4.4"
r2r = "0.9"
futures = "0.3"
